In [16]:
import numpy as np

In [17]:
from math import sqrt

In [18]:
a = np.matrix("1,1,1;0.05,0.07,0;0.05,0,0.06")
b = np.matrix("50000;2250;1400")
x = np.linalg.solve(a, b)

In [19]:
x

matrix([[10000.],
        [25000.],
        [15000.]])

In [21]:
a = np.matrix("1,1,1; 2,0,1;2,1,0")
b = np.matrix("1328;1208;1428")
x = np.linalg.solve(a, b)

In [22]:
x

matrix([[436.],
        [556.],
        [336.]])

In [23]:
a = np.matrix(f"{sqrt(3)},0,{sqrt(3)};{sqrt(6)},0.5,0;1,0.33,0")
b = np.matrix("1;1;1")
x = np.linalg.solve(a, b)

In [24]:
x

matrix([[-0.55135442],
        [ 4.70107401],
        [ 1.12870469]])

In [25]:
a = np.matrix("1,1,1; 9,3,1;1,-1,1")
b = np.matrix("12;54;2")
x = np.linalg.solve(a, b)

In [26]:
x

matrix([[4.],
        [5.],
        [3.]])

In [27]:
def get_polynom(coords):
    i = len(coords)
    a = ""
    b = ""
    for coord in coords:
        start = 0
        str_len_fin_start = len(a)
        for el in range(i):
            a = str(a[:0]) + str(f"{(int(coord[0]))**(int(start))}") + "," + str(a[0:])
            start += 1
        str_len_fin = len(a)
        str_len = str_len_fin - str_len_fin_start
        a = a[:str_len - 1] + ";" + a[str_len:]
        b = f"{coord[1]};" + b[0:]
    a_matrix = np.matrix(a[:-1])
    b_matrix = np.matrix(b[:-1])
    return np.linalg.solve(a_matrix, b_matrix)

In [28]:
coords = ([(1,12), (3,54), (-1,2)])
solve = get_polynom(coords)
# print(solve)

In [29]:
solve

matrix([[4.],
        [5.],
        [3.]])